### ISSUE TITLE
Building Permits - New As-Built AP Type for PDox

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#38] opened 2020-01-17 14:44 UTC
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2288
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2288) 

**Request:**
We would like to have this as a future phase that once a SWM permit reach guarantee release inspection and the as built submission is required, we would like to have an a/p type created for as built that will be routed and reviewed through project dox with GIS / OSER review in addition to ECS review - we would like to have this because GIS currenlty receives CD's with CAD files for the as builts and CAD files cannot be uploaded to IPS through R4C therefore we are not able to improve our current process and would like to.

**Comment by ABonomo21** [comment] 2020-02-11 01:07
I think this is a nice to have but can be a phase 2 for sure. - thoughts from gary ??

**Comment by AReed327** [comment] 2020-02-11 15:10
CAD files cannot be uploaded to PDOX due to size constraints. Adding this as a reminder. Engineers had a large issue with this at our outreach meeting and it was confirmed by Dustin.

**Comment by ABonomo21** [comment] 2020-02-11 15:26
@JuanitaMiles JuanitaMiles added Needs Discussion Legacy: Post Go Live Correction and removed Needs Discussion labels 28 days ago
@ABonomo21
 
Collaborator
ABonomo21 commented now
DUPLICATE

@ABonomo21 ABonomo21 closed this now
@ABonomo21
 
 
Leave a comment
Attach files to your comment
Attach files by dragging & dropping, selecting or pasting them.
Remember, contributions to this repository should follow our GitHub Community Guidelines.
AssigneesNo one—

**Comment by ABonomo21** [comment] 2020-02-11 15:45
moved

**Comment by ABonomo21** [comment] 2020-03-04 23:48
re-opening and closed in current github repository  will work on this after July - Definitely something we would like completed but with time we know this has to be a phase 2. okay per ash gary with meeting 3.4.2020

**Comment by ABonomo21** [comment] 2021-04-06 19:03
no longer required- new as-built process established for ECS applications

**Closed by ABonomo21** 2021-04-06 19:03 UTC
